version: "3.3"

services:
  db:
    image: postgres:14
    container_name: pension_db
    environment:
      POSTGRES_DB: pension_db
      POSTGRES_USER: pension_user
      POSTGRES_PASSWORD: pension_password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres-data:
